---
title: "R Notebook"
output: html_notebook
---

# Load and Prep
```{r}
library(ggplot2)
library(dplyr)
library(tidytext)

dir_of_data <- "../vis/src/data/"
file_of_data <- "fullData_cutted.csv"
data_original <- read.csv(paste(dir_of_data, file_of_data, sep = ""))
file_of_data_words <- "full_word_level.csv"
data_words_original <- read.csv(paste(dir_of_data, file_of_data_words, sep = ""))

# Process
data_log <- data_original %>%
  rename(datetime=date) %>%
  mutate(date=as.Date(datetime),
         time=times(format(as.POSIXct(datetime, "UTC", "%Y-%m-%dT%H:%M:%S"), "%H:%M:%S"))) %>%
  filter(date >= as.Date("2017-01-01"), 
         action != "phone_call") %>%
  left_join(data_words_original %>% count(id), by=c("id")) %>%
  rename(word_count=n) %>%
  mutate_at(c("word_count"), ~replace(., is.na(.), 0))

data_words <- data_words_original %>%
  inner_join(data_log, by=c("id", "from"))


```

# Timeline
## Overall Time Series
```{r}
data <- data_log %>%
  group_by(date) %>%
  summarise(n=n()) %>%
  ungroup()

data %>%
  ggplot(aes(x = date, y = n)) +
  geom_bar(stat="identity") +
  theme_bw()
```
## Separated Time Series
```{r}
data <- data_log %>%
  group_by(date, from) %>%
  summarise(n=n()) %>%
  ungroup()

data %>%
  ggplot(aes(x = date, y = n, fill = from)) +
  geom_bar(stat="identity", position = "identity", alpha = 0.5) +
  theme_bw()
```
## Word count
```{r}
data <- data_log %>%
  group_by(date, from) %>%
  summarise(words=sum(word_count)) %>%
  ungroup()

data %>%
  ggplot(aes(x = date, y = words, fill = from)) +
  geom_bar(stat="identity", position = "identity", alpha = 0.5) +
  theme_bw()
```


## media_type
```{r}
data <- data_log %>%
  group_by(date, from, media_type) %>%
  summarise(n=n()) %>%
  ungroup()

data %>%
  ggplot(aes(x = date, y = n, fill = media_type)) +
  geom_bar(stat="identity") +
  facet_grid(from ~ .) +
  theme_bw()
```


# Calendar Heatmap
```{r}
source("libs/calendarHeat.R")

data <- data_log %>%
  group_by(date) %>%
  summarise(n=n()) %>%
  ungroup()

calendarHeat(data$date, data$n, ncolors = 99, color = "g2r", varname="Bubble Count")
```
# 24-hr Vis
```{r}
library(lubridate)
library(scales)

data_log %>%
  ggplot(aes(x=time)) +
  geom_histogram(binwidth =0.001) +
  scale_x_time(breaks = "minute", labels=time_format("%H")) #？？？
```


# Words
## Word Frequency - with stopwords
```{r}
temp_data <- data_words %>% 
  group_by(word) %>% 
  summarise(total_n=n()) %>%
  ungroup()

data_words %>%
  group_by(word, from) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  left_join(temp_data, by=c("word")) %>%
  filter(total_n > 1200) %>%
  mutate(word = reorder(word, total_n)) %>%
  ggplot(aes(x = word, y = n, fill = from)) +
  theme(text = element_text(family = "Heiti SC Light")) +
  geom_col() +
  coord_flip() +
  theme_bw(base_family="Heiti SC Light") +
  labs(y = "Word Frequency")

```
## Word Frequency - without stopwords
```{r}
source('libs/stopwords_chinese.R')

temp_data <- data_words %>% 
  group_by(word) %>% 
  summarise(total_n=n()) %>%
  ungroup()

data_words %>%
  group_by(word, from) %>%
  summarise(n=n()) %>%
  ungroup() %>%
  left_join(temp_data, by=c("word")) %>%
  anti_join(stopwords_chinese) %>%
  anti_join(get_stopwords()) %>%
  filter(total_n > 500) %>%
  mutate(word = reorder(word, total_n)) %>%
  ggplot(aes(x = word, y = n, fill = from)) +
  theme(text = element_text(family = "Heiti SC Light")) +
  geom_col() +
  coord_flip() +
  theme_bw(base_family="Heiti SC Light") +
  labs(y = "Word Frequency")
```
## Word Cloud
```{r}
library(wordcloud)
data_words %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))

```



